=== BytewaveMLP/pridemoji/schemas/build-config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "build-config.schema.json",
    "title": "Pridemoji build configuration",
    "description": "The Pridemoji build configuration.",
    "type": "object",
    "properties": {
        "static": {
            "description": "A list of static svg files to render.",
            "type": "array",
            "items": {
                "description": "The path to an SVG file. Allows wildcards.",
                "type": "string"
            }
        },
        "combinations": {
            "description": "A list of emoji combinations to generate.",
            "type": "array",
            "items": {
                "description": "An emoji combination to generate.",
                "type": "object",
                "properties": {
                    "templates": {
                        "description": "A list of the emoji templates to use, or a wildcard to include all templates.",
                        "oneOf": [
                            {
                                "type": "string",
                                "const": "*"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/identifier"
                                }
                            }
                        ]
                    },
                    "prides": {
                        "description": "A list of pride colors to use, or a wildcard to include all prides.",
                        "oneOf": [
                            {
                                "type": "string",
                                "const": "*"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/identifier"
                                }
                            }
                        ]
                    }
                },
                "additionalProperties": false,
                "required": [
                    "templates",
                    "prides"
                ]
            }
        },
        "templates": {
            "description": "A map of emoji templates.",
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z-]+$": {
                    "description": "An emoji template.",
                    "type": "object",
                    "properties": {
                        "name": {
                            "description": "The full name of the template.",
                            "type": "string"
                        },
                        "templateFile": {
                            "description": "A path to the SVG template file.",
                            "type": "string"
                        },
                        "stripesId": {
                            "description": "The id of the element to draw stripes inside.",
                            "type": "string"
                        },
                        "stripesRotation": {
                            "description": "The angle the stripes should be drawn at.",
                            "type": "integer"
                        },
                        "accentIds": {
                            "description": "An array of accent containers to use for accent colors.",
                            "type": "array",
                            "items": {
                                "description": "The id of the accent element.",
                                "type": "string"
                            }
                        }
                    },
                    "required": [
                        "name",
                        "templateFile",
                        "stripesId"
                    ],
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        },
        "prides": {
            "description": "A map of pride colors.",
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z-]+$": {
                    "type": "object",
                    "description": "A pride",
                    "properties": {
                        "name": {
                            "description": "The full name of the pride.",
                            "type": "string"
                        },
                        "stripes": {
                            "description": "The pride's stripe colors.",
                            "type": "array",
                            "items": {
                                "description": "The hexidecimal color of the stripe.",
                                "type": "string",
                                "format": "color-hex"
                            }
                        },
                        "accents": {
                            "description": "The pride accents. Defaults to the first stripe color.",
                            "type": "object",
                            "patternProperties": {
                                "^[a-zA-Z-]+$": {
                                    "description": "The hexidecimal accent color.",
                                    "type": "string",
                                    "format": "color-hex"
                                }
                            }
                        },
                        "variants": {
                            "description": "A map of color variations for a pride.",
                            "type": "object",
                            "patternProperties": {
                                "^[a-zA-Z-]+$": {
                                    "type": "object",
                                    "description": "A pride",
                                    "properties": {
                                        "name": {
                                            "description": "The full name of the pride.",
                                            "type": "string"
                                        },
                                        "stripes": {
                                            "description": "The pride stripes.",
                                            "type": "array",
                                            "items": {
                                                "description": "The pride stripe color.",
                                                "type": "string",
                                                "format": "color-hex"
                                            }
                                        },
                                        "accents": {
                                            "description": "The pride accents. Defaults to the first stripe color.",
                                            "type": "object",
                                            "patternProperties": {
                                                "^[a-zA-Z-]+$": {
                                                    "description": "The hexidecimal accent color.",
                                                    "type": "string",
                                                    "format": "color-hex"
                                                }
                                            }
                                        }
                                    },
                                    "required": [
                                        "name"
                                    ],
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false
                        }
                    },
                    "required": [
                        "name",
                        "stripes"
                    ],
                    "additionalProperties": false
                },
                "uniqueItems": true
            }
        }
    },
    "required": [
        "combinations",
        "templates",
        "prides"
    ],
    "additionalProperties": false,
    "definitions": {
        "identifier": {
            "type": "string",
            "pattern": "^[a-zA-Z-]+$"
        }
    }
}

=== BytewaveMLP/pridemoji/build-config.json
{
    "static": [
        "./assets/**/*.svg"
    ],
    "combinations": [
        {
            "templates": "*",
            "prides": "*"
        }
    ],
    "templates": {
        "flag": {
            "name": "Flag",
            "templateFile": "./templates/flag.svg",
            "stripesId": "stripes",
            "stripesRotation": 0
        },
        "syringe": {
            "name": "Syringe",
            "templateFile": "./templates/syringe.svg",
            "stripesId": "stripes",
            "stripesRotation": -45,
            "accentIds": [
                "drop1",
                "drop2"
            ]
        },
        "heart": {
            "name": "Heart",
            "templateFile": "./templates/heart.svg",
            "stripesId": "stripes",
            "stripesRotation": 0
        },
        "heart-d": {
            "name": "Diagonal Heart",
            "templateFile": "./templates/heart.svg",
            "stripesId": "stripes",
            "stripesRotation": 45
        },
        "ghost": {
            "name": "Ghost",
            "templateFile": "./templates/ghost.svg",
            "stripesId": "stripes",
            "stripesRotation": 0
        },
        "cat": {
            "name": "Kitty",
            "templateFile": "./templates/cat.svg",
            "stripesId": "stripes",
            "stripesRotation": 0
        }
    },
    "prides": {
        "ace": {
            "name": "Asexual",
            "stripes": [
                "#000000",
                "#959595",
                "#ffffff",
                "#670066"
            ],
            "accents": {
                "drop1": "#670066",
                "drop2": "#670066"
            }
        },
        "agender": {
            "name": "Agender",
            "stripes": [
                "#000000",
                "#bcc5c6",
                "#ffffff",
                "#b5f582",
                "#ffffff",
                "#bcc5c6",
                "#000000"
            ]
        },
        "aro": {
            "name": "Aromantic",
            "stripes": [
                "#3ca542",
                "#a8d377",
                "#fefefe",
                "#a9a9a9",
                "#000000"
            ]
        },
        "bi": {
            "name": "Bisexual",
            "stripes": [
                "#d70170",
                "#d70170",
                "#734f94",
                "#0039a7",
                "#0039a7"
            ]
        },
        "enby": {
            "name": "Non-Binary",
            "stripes": [
                "#fff433",
                "#ffffff",
                "#9b59d0",
                "#2d2d2d"
            ]
        },
        "gay": {
            "name": "Gay",
            "stripes": [
                "#e50000",
                "#ff8d00",
                "#ffee00",
                "#008121",
                "#004cff",
                "#760188"
            ]
        },
        "fluid": {
            "name": "Genderfluid",
            "stripes": [
                "#ff76a3",
                "#ffffff",
                "#bf11d7",
                "#000000",
                "#2f3cbe"
            ]
        },
        "genderqueer": {
            "name": "Genderqueer",
            "stripes": [
                "#b67edc",
                "#ffffff",
                "#4b8124"
            ]
        },
        "lesbian": {
            "name": "Lesbian",
            "stripes": [
                "#d72c00",
                "#ef7427",
                "#ff9856",
                "#ffffff",
                "#d162a6",
                "#b75592",
                "#a50162"
            ]
        },
        "pan": {
            "name": "Pansexual",
            "stripes": [
                "#ff218c",
                "#fed800",
                "#21b1ff"
            ]
        },
        "polyamorous": {
            "name": "Polyamorous",
            "stripes": [
                "#ff7eb5",
                "#ffe900",
                "#4e4e4e",
                "#00f2ff",
                "#ab00ff"
            ]
        },
        "polysexual": {
            "name": "Polysexual",
            "stripes": [
                "#f61cb9",
                "#07d569",
                "#1c92f6"
            ]
        },
        "trans": {
            "name": "Transgender",
            "stripes": [
                "#5bcefa",
                "#f5a9b8",
                "#ffffff",
                "#f5a9b8",
                "#5bcefa"
            ],
            "accents": {
                "drop1": "#5bcefa",
                "drop2": "#f5a9b8"
            },
            "variants": {
                "blue": {
                    "name": "Blue",
                    "accents": {
                        "drop1": "#5bcefa",
                        "drop2": "#5bcefa"
                    }
                },
                "pink": {
                    "name": "Pink",
                    "accents": {
                        "drop1": "#f5a9b8",
                        "drop2": "#f5a9b8"
                    }
                }
            }
        },
        "pastelorangegender": {
            "name": "Pastelorangegender",
            "stripes": [
                "#ddd4e3",
                "#ffffff",
                "#fee7da",
                "#ffd8be",
                "#ffc9a7",
                "#ddd4e3"
            ],
            "accents": {
                "drop1": "#ffc9a7",
                "drop2": "#ffc9a7"
            }
        },
        "aroace": {
            "name": "Aromantic Asexual",
            "stripes": [
                "#e38d00",
                "#ecce00",
                "#ffffff",
                "#62afdd",
                "#1a3555"
            ],
            "accents": {
                "drop1": "#e38d00",
                "drop2": "#e38d00"
            },
            "variants": {
                "alt": {
                    "name": "Alt",
                    "stripes": [
                        "#000000",
                        "#670066",
                        "#959595",
                        "#ffffff",
                        "#a8d377",
                        "#3ca542"
                    ],
                    "accents": {
                        "drop1": "#670066",
                        "drop2": "#3ca542"
                    }
                }
            }
        }
    }
}
